server:
  port: 8088
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    username: postgres
    password: 1106
    url: jdbc:postgresql://localhost:5432/order_service_db


    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

services:
  inventory-url: http://ORDER-SERVICE/order
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848
