server:
  port: 8083
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order_service_db


    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

services:
  inventory-url: http://ORDER-SERVICE/order
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
